baseurl: "http://example.org/"
languageCode: "en-us"
title: "infcode"
theme: "xmin"
googleAnalytics: "G-9ZZ9N6HS97"
disqusShortname: "infc0de"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "infcode - c/c++ and gamedev"
  footer: "Public domain, no rights reserved."

markup:
  goldmark:
    renderer:
      unsafe: true
